# Theme and Language
theme: jekyll-theme-chirpy
lang: en
timezone: America/New_York

# Site Identity
title: Rajasundaram Mathiazhagan
tagline: Robotics • Perception • AI
description: >-
  Portfolio of a robotics engineer passionate about autonomy, perception, and intelligent systems.
url: "https://rajasundaramm.github.io"
baseurl: "/rajasundaram-portfolio" # IMPORTANT: Ensure this matches your GitHub repository name if it's a project page.

# Author Info (Used for the sidebar)
github:
  username: rajasundaramm

social:
  name: Rajasundaram Mathiazhagan # Your name displayed in the sidebar
  email: rm6584@nyu.edu
  links:
    - https://www.linkedin.com/in/rajasundaramm/
    - https://github.com/rajasundaramm

# Avatar and Preview Image
avatar: "/assets/img/profile.jpg" # Upload your profile picture here (e.g., profile.jpg)
social_preview_image: "/assets/img/preview.png" # Optional: For social media previews

# Appearance
theme_mode: light # options: light, dark, or leave blank for auto-switch

# Analytics (optional)
analytics:
  google:
    id: "" # Add your GA tag if needed

# PWA (Progressive Web App)
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:
      - "/admin"

# Comments (disabled for portfolio)
comments:
  provider:

# Posts (Generally not used for a pure portfolio, but keep if you plan a blog)
paginate: 0 # Set to 0 to disable pagination for posts if not blogging
toc: true # Enable Table of Contents for long pages/projects

# Collections for vertical tabs and content
collections:
  tabs:
    output: true
    sort_by: order
  education: # NEW: Collection for education entries
    output: true
    permalink: /education/:title/ # Or /education/:name/
    sort_by: order # To sort entries by order
  projects: # NEW: Collection for projects
    output: true
    permalink: /projects/:name/ # e.g., /projects/my-robot-project/
    sort_by: order # To sort projects within their categories
  experience: # NEW: Collection for experience entries
    output: true
    permalink: /experience/:name/ # e.g., /experience/my-internship/
    sort_by: order # To sort experiences by order

defaults:
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/ # e.g., /about-me/, /education/, /projects/, /experience/
  - scope:
      path: ""
      type: education # Default layout for education entries
    values:
      layout: education_entry # You'll create _layouts/education_entry.html
      comments: false
  - scope:
      path: ""
      type: projects # Default layout for individual project pages (though we'll link directly to GitHub)
    values:
      layout: project_tile # You'll create _layouts/project_tile.html (though it might be rendered on the projects page)
      comments: false
  - scope:
      path: ""
      type: experience # Default layout for individual experience pages
    values:
      layout: experience_entry # You'll create _layouts/experience_entry.html
      comments: false
  - scope:
      path: ""
      type: posts # Keep if you plan a blog, otherwise this block can be removed
    values:
      layout: post
      toc: true
      comments: false
      permalink: /posts/:title/

# SASS/CSS
sass:
  style: compressed

# HTML Compression
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# SEO
webmaster_verifications: {}

# Exclude files from the build
exclude:
  - "*.gem"
  - "*.gemspec"
  - README.md
  - LICENSE
  - node_modules
  - vendor
  - package*.json
  - "*.config.js"

# _config.yml (partial)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-paginate # <--- ENSURE THIS LINE IS PRESENT
