# Theme and Language
theme: jekyll-theme-chirpy
lang: en
timezone: America/New_York

# Site Identity
title: Rajasundaram Mathiazhagan
tagline: Robotics • Perception • AI
description: >-
  Portfolio of a robotics engineer passionate about autonomy, perception, and intelligent systems.
url: "https://rajasundaramm.github.io"
baseurl: "/rajasundaram-portfolio" # don’t include trailing slash in url

# Author Info
github:
  username: rajasundaramm

social:
  name: Rajasundaram Mathiazhagan
  email: rm6584@nyu.edu
  links:
    - https://www.linkedin.com/in/rajasundaramm/
    - https://github.com/rajasundaramm

# Avatar and Preview Image
avatar: "/assets/img/profile.jpg"  # upload your image to /assets/img/ and use that path
social_preview_image: "/assets/img/preview.png"  # optional

# Appearance
theme_mode: light  # options: light, dark, or leave blank for auto-switch

# Analytics (optional)
analytics:
  google:
    id: ""  # Add your GA tag if needed

# PWA (Progressive Web App)
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:
      - "/admin"

# Comments (disabled for portfolio)
comments:
  provider:

# Posts
paginate: 10
toc: true

# Collections for vertical tabs
collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      toc: true
      comments: false
      permalink: /posts/:title/

# SASS/CSS
sass:
  style: compressed

# HTML Compression
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# SEO
webmaster_verifications: {}

# Jekyll Archives (optional)
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# Exclude files from the build
exclude:
  - "*.gem"
  - "*.gemspec"
  - README.md
  - LICENSE
  - node_modules
  - vendor
  - package*.json
  - "*.config.js"
