# ==============================================================================
# Jekyll Configuration File for Chirpy Theme
# ==============================================================================

# ------------------------------------------------------------------------------
# Theme and Language Settings
# ------------------------------------------------------------------------------
theme: jekyll-theme-chirpy # IMPORTANT: This must be present for Jekyll to find theme assets
lang: en # Site language code (e.g., 'en', 'zh', 'fr')
timezone: America/New_York # Set your site's timezone (e.g., 'Asia/Kolkata', 'Europe/Paris')

# ------------------------------------------------------------------------------
# Site Identity and SEO
# ------------------------------------------------------------------------------
title: Rajasundaram Mathiazhagan
tagline: Robotics • Perception • AI
description: >-
  Portfolio of a robotics engineer passionate about autonomy, perception, and intelligent systems.
url: "https://rajasundaramm.github.io" # Your GitHub Pages URL (e.g., "https://username.github.io")
baseurl:
  "/rajasundaram-portfolio" # Your repository name if it's a project page (e.g., "/my-repo")
  # Leave blank ("") if it's a user/organization page (username.github.io)

# ------------------------------------------------------------------------------
# Author Information (Used for the sidebar and metadata)
# ------------------------------------------------------------------------------
github:
  username: rajasundaramm # Your GitHub username

social:
  name: Rajasundaram Mathiazhagan # Your full name displayed in the sidebar
  email: rm6584@nyu.edu
  links:
    - https://www.linkedin.com/in/rajasundaramm/ # LinkedIn profile link
    - https://github.com/rajasundaramm # GitHub profile link

# Avatar and Social Preview Image
avatar: "/assets/img/profile.jpg" # Path to your profile picture (e.g., /assets/img/profile.jpg)
social_preview_image: "/assets/img/preview.png" # Optional: For social media link previews

# ------------------------------------------------------------------------------
# Site Appearance and Features
# ------------------------------------------------------------------------------
theme_mode: light # Options: 'light', 'dark', or leave blank for auto-switch based on user's system preferences

# Analytics (optional)
analytics:
  google:
    id: "" # Your Google Analytics tracking ID (e.g., "G-XXXXXXXXXX"). Leave blank if not used.

# PWA (Progressive Web App)
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:
      - "/admin" # Paths to exclude from PWA caching

# Comments (disabled for portfolio based on your config)
comments:
  provider: # Leave blank to disable comments

# Post/Page Settings (Adjust if you plan to add blog posts)
paginate: 0 # Set to 0 to disable pagination. Set to a number (e.g., 5) to enable pagination for blog posts.
toc: true # Enable Table of Contents for long pages/posts

# ------------------------------------------------------------------------------
# Collections for Custom Content (Education, Projects, Experience)
# ------------------------------------------------------------------------------
collections:
  tabs:
    output: true
    sort_by: order # Used for sorting tabs (e.g., About, Education, Projects)
  education: # Custom collection for education entries
    output: true
    permalink: /education/:title/ # Permalink structure (e.g., /education/nyu-masters/)
    sort_by: order # Sort education entries (e.g., by chronological order)
  projects: # Custom collection for project entries
    output: true
    permalink: /projects/:name/ # Permalink structure (e.g., /projects/my-robot-project/)
    sort_by: order # Sort project entries
  experience: # Custom collection for experience entries
    output: true
    permalink: /experience/:name/ # Permalink structure (e.g., /experience/my-internship/)
    sort_by: order # Sort experience entries

# ------------------------------------------------------------------------------
# Default Front Matter for Collections (Important for Layouts)
# ------------------------------------------------------------------------------
defaults:
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/ # e.g., /about-me/, /education/, /projects/, /experience/
  - scope:
      path: ""
      type: education # Default layout for individual education entries
    values:
      layout: education_entry # <<< IMPORTANT: This layout file (_layouts/education_entry.html) MUST EXIST.
      comments: false
  - scope:
      path: ""
      type: projects # Default layout for individual project pages
    values:
      layout: project_tile # <<< IMPORTANT: This layout file (_layouts/project_tile.html) MUST EXIST.
      comments: false
  - scope:
      path: ""
      type: experience # Default layout for individual experience pages
    values:
      layout: experience_entry # <<< IMPORTANT: This layout file (_layouts/experience_entry.html) MUST EXIST.
      comments: false
  - scope:
      path: ""
      type: posts # Default layout for standard blog posts (if you add a blog later)
    values:
      layout: post
      toc: true
      comments: false
      permalink: /posts/:title/ # e.g., /posts/my-first-post/

# ------------------------------------------------------------------------------
# SASS/CSS and HTML Compression
# ------------------------------------------------------------------------------
sass:
  style: compressed # Minify CSS files

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development] # Don't compress HTML in development environment

# ------------------------------------------------------------------------------
# SEO Webmaster Verifications (for Google, Bing, etc.)
# ------------------------------------------------------------------------------
webmaster_verifications: {} # Fill in your verification codes here if needed

# ------------------------------------------------------------------------------
# Files/Directories to Exclude from Build
# ------------------------------------------------------------------------------
exclude:
  - "*.gem"
  - "*.gemspec"
  - README.md
  - LICENSE
  - node_modules
  - vendor # Excludes the 'vendor' directory where Bundler installs gems
  - package*.json
  - "*.config.js"

# ------------------------------------------------------------------------------
# Jekyll Plugins (CRITICAL for GitHub Pages deployment)
# ------------------------------------------------------------------------------
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-paginate # Keep this if you use `paginate` in your config, otherwise remove from Gemfile and here
