# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      ["master"] # <--- IMPORTANT: Changed to 'master' based on your 'git push origin master' success.
      # If your default branch on GitHub is 'main', change this back to 'main'.
      # If you changed your local branch to 'main' and pushed, ensure this matches.

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the start and latest queued.
# However, it is also shown here as an example to set up a cancel-in-progress deployment.
concurrency:
  group: "github-pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2" # Keep this at '3.1' or '3.2'
          bundler-cache: true # This still ensures your gems are installed from Gemfile.lock
      - name: Build with Jekyll # <--- IMPORTANT CHANGE STARTS HERE!
        run: |
          bundle exec jekyll build --source . --destination _site
          # Ensure that the _site directory exists and is not empty
          ls -R _site
        # <--- IMPORTANT CHANGE ENDS HERE!
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
